risky: true
version: 7
tab-width: 2
use-tabs: true
enabled:
  - linebreak_after_opening_tag
  - blank_line_before_statement
  - trailing_comma_in_multiline_array
  - date_time_immutable
  - no_trailing_whitespace
  - no_unused_imports
  - align_double_arrow
  - align_equals
disabled:
  - no_trailing_comma_in_list_call
finder:
  exclude:
    - 'node_modules'
    - 'vendor'
  name: '*.php'
