name: bingo-functional CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2']
    name: PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ matrix.php }}-composer-
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Purge project of any phpunit cache files
        run: find . -name "*.phpunit*" -type f -print0 | xargs -0 /bin/rm -f
      - name: Run test suite
        run: vendor/bin/phpunit --coverage-clover=coverage.xml
      - name: Get coverage report from codecov
        run: bash <(curl -s https://codecov.io/bash)
